/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDefaultApi.h"

#include "OpenAPIHTTPValidationError.h"
#include "OpenAPILoginInfo.h"
#include "OpenAPILoginResponse.h"

namespace OpenAPI
{

/* Mmologin

*/
class OPENAPI_API OpenAPIDefaultApi::MmologinMmologinPostRequest : public Request
{
public:
    virtual ~MmologinMmologinPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPILoginInfo OpenAPILoginInfo;
};

class OPENAPI_API OpenAPIDefaultApi::MmologinMmologinPostResponse : public Response
{
public:
    virtual ~MmologinMmologinPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPILoginResponse Content;
};

}
