/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIValidationError.h"

namespace OpenAPI
{

/*
 * OpenAPIHTTPValidationError
 *
 * 
 */
class OPENAPI_API OpenAPIHTTPValidationError : public Model
{
public:
    virtual ~OpenAPIHTTPValidationError() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<TArray<OpenAPIValidationError>> Detail;
};

}
