/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIInventoryBase
 *
 * 
 */
class OPENAPI_API OpenAPIInventoryBase : public Model
{
public:
    virtual ~OpenAPIInventoryBase() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Id;
	int32 CharacterId = 0;
	int32 Slot = 0;
	FString Item;
	int32 Amount = 0;
};

}
