/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPICharacterBase
 *
 * 
 */
class OPENAPI_API OpenAPICharacterBase : public Model
{
public:
    virtual ~OpenAPICharacterBase() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	int32 Id = 0;
	TOptional<int32> UserId;
	FString Name;
	int32 _Class = 0;
	int32 Gender = 0;
	int32 Health = 0;
	int32 Mana = 0;
	int32 Level = 0;
	int32 Experience = 0;
	int32 Clan = 0;
	TOptional<int32> Posx;
	TOptional<int32> Posy;
	TOptional<int32> Posz;
	double RotationYaw;
	TOptional<FString> EquipHead;
	TOptional<FString> EquipChest;
	TOptional<FString> EquipHands;
	TOptional<FString> EquipFeet;
	TOptional<FString> Hotbar0;
	TOptional<FString> Hotbar1;
	TOptional<FString> Hotbar2;
	TOptional<FString> Hotbar3;
	TOptional<FString> Hotbar4;
	TOptional<FString> Hotbar5;
	TOptional<FString> Hotbar6;
	TOptional<FString> Hotbar7;
	TOptional<FString> Hotbar8;
	TOptional<FString> Hotbar9;
	TOptional<FString> Hotbar10;
	TOptional<FString> Hotbar11;
	TOptional<FString> Hotbar12;
	TOptional<FString> Hotbar13;
	TOptional<FString> Hotbar14;
	TOptional<FString> Hotbar15;
	TOptional<FString> Hotbar16;
	TOptional<FString> Hotbar17;
	TOptional<FString> Hotbar18;
	TOptional<FString> Hotbar19;
	TOptional<FString> Hotbar20;
	TOptional<FString> Hotbar21;
	TOptional<FString> Hotbar22;
	TOptional<FString> Hotbar23;
	TOptional<FString> Hotbar24;
	TOptional<FString> Hotbar25;
	TOptional<FString> Hotbar26;
	TOptional<FString> Hotbar27;
	TOptional<FString> Hotbar28;
	TOptional<FString> Hotbar29;
	int32 Stamina = 0;
	TOptional<int32> RealmId;
	TOptional<int32> RaceId;
};

}
