/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIValidationError.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIValidationError::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Loc.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("loc")); WriteJsonValue(Writer, Loc.GetValue());
	}
	if (Msg.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("msg")); WriteJsonValue(Writer, Msg.GetValue());
	}
	if (Type.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("type")); WriteJsonValue(Writer, Type.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIValidationError::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("loc"), Loc);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("msg"), Msg);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("type"), Type);

	return ParseSuccess;
}

}
