/**
 * Daor
 * Api for DAOR MMORPG server.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: julien.lebourg@ctg.lu
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIHTTPValidationError.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIHTTPValidationError::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Detail.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("detail")); WriteJsonValue(Writer, Detail.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIHTTPValidationError::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("detail"), Detail);

	return ParseSuccess;
}

}
